GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH HTTP/1.1
###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS HTTP/1.1
###

GET http://localhost:3000/todos/?status=TO%20DO HTTP/1.1
###

GET http://localhost:3000/todos/?priority=HIG HTTP/1.1
###

GET http://localhost:3000/todos/?search_q=Buy HTTP/1.1
###

GET http://localhost:3000/todos/?category=WORK&status=DONE HTTP/1.1
###

GET http://localhost:3000/todos/6/ HTTP/1.1
###

GET http://localhost:3000/agenda/?date=2021-02-22 HTTP/1.1
###

POST http://localhost:3000/todos/ HTTP/1.1
Content-Type:  application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###

PUT http://localhost:3000/todos/6/ HTTP/1.1
Content-Type: application/json

{
  "status": "DONE"
}
###

DELETE http://localhost:3000/todos/6/ HTTP/1.1
###